spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 이메일@gmail.com
    password: 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
cloud:
  aws:
    s3:
      bucket: bit-palette
    region:
      static: ap-northeast-2
